"""addCar

Revision ID: 024effe3e8d6
Revises: c21b8a42bd09
Create Date: 2024-05-29 16:53:30.681717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024effe3e8d6'
down_revision = 'c21b8a42bd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('car_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
