"""addRelationship

Revision ID: 6a94d354c6f4
Revises: 024effe3e8d6
Create Date: 2024-05-29 16:54:17.751779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a94d354c6f4'
down_revision = '024effe3e8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['car_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
